version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - blog_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
    - blog_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - blog_network

  nginx:
    image: nginx:alpine
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"  # nginx будет доступен на порту 80
    depends_on:
      - backend
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge

volumes:
  db_data:
